### ISSUE TITLE
How to now be banned

### ISSUE THREAD

**Issue by SetUpSim** [luizmlo/py-lightshot-dowloader#6]
If you add time.sleep(0.25) (you can change amount of seconds if you want) in main() after thread.start() (you have to add "import time" at the beginning of file firstly), you will not be banned for ~4 minutes (in my case). You can also change your IP using VPN every time you get banned

**Comment by luizmlo** [comment]
Very good point, I'll be adding the sleep first, then I'll look into the VPN
